### ISSUE TITLE
Inconsistent colors in the tool window

### ISSUE THREAD

**Issue by lsw9521** [marko-mihajlovic/poimandres-jetbrains#1]
## I like this theme a lot, however, it does not perform well in the Git tool window, the color is not uniform! may you fix it?
<img width="960" alt="截图_20230225150059" src="https://user-images.githubusercontent.com/64994513/221343637-c91fb468-a340-499f-a10f-e3b678c45f84.png">

**Comment by lsw9521** [comment]
If you can provide more similar pure color themes, it will be more appreciated! At least one light color theme is required！

**Comment by marko-mihajlovic** [comment]
> I like this theme a lot, however, it does not perform well in the Git tool window, the color is not uniform! may you fix it?  

Sure, will fix it in next update.


> If you can provide more similar pure color themes, it will be more appreciated! At least one light color theme is required！

What do you mean?

**Comment by lsw9521** [comment]
First of all thank you for replying! Here are some of my suggestions.
1. Can you offer more solid color options, Pack more dark themes and at
least one light theme in this plugin?
2. Hide the search box border just like the `True Black` Theme Do!
<img width="960" alt="截图_20230226081510" src="https://user-images.githubusercontent.com/64994513/221385705-04b03bb8-2b25-4e93-be58-37b0f38c66c8.png">
3. Do you have any good ways to hide the scroll bar？
<img width="960" alt="截图_20230226083536" src="https://user-images.githubusercontent.com/64994513/221386034-7543de45-86fa-43c4-af0e-f893589d7649.png">

**Comment by marko-mihajlovic** [comment]
> 1. Can you offer more solid color options, Pack more dark themes and at
least one light theme in this plugin?  

As this discussed in [this issue](https://github.com/drcmda/poimandres-theme/issues/18), light themes are all very similar, so it doesn't make sense to make a new one.
At least for now, I will not make more dark themes, I like this one.

<br>

> 2. Hide the search box border just like the True Black Theme Do!  

Original vsc theme has borders around inputs, so I will not be changing that.

![image](https://user-images.githubusercontent.com/88029880/221416768-140dac9a-d7a4-4371-ae37-81b5838c76b4.png)

<br>

> 3. Do you have any good ways to hide the scroll bar？

That sounds like a bad idea. Scrollbar is important visual element.
Original vsc theme example:

![image](https://user-images.githubusercontent.com/88029880/221417621-769b6a2b-bf04-466d-bc07-2eb2fdf0f714.png)

**Comment by lsw9521** [comment]
Thank you !  ^_^
